### ISSUE TITLE
User stays logged in after cookie deletion

### ISSUE THREAD

**Issue by OneWithTheCore** [v0lture/project-junebug#19]
After deleting cookies and refreshing, I remain logged in, but I can still log in again, as seen in screenshot below:

![image](https://cloud.githubusercontent.com/assets/9288431/26381722/c6575bdc-3ff4-11e7-8fb8-f198715e9511.png)

**Comment by OneWithTheCore** [comment]
This was found to be due to come caching issues. Bug not reproducible after caching issue fixed. Bug is to be closed

**Comment by lowlandghost** [comment]
Similar to issue #13.
