### ISSUE TITLE
Third page doesn't show up until return to the first page then back to second

### ISSUE THREAD

**Issue by OneWithTheCore** [v0lture/project-junebug#20]
The third page does not exist until I go to the second page, then the first, then back to the second which is when the third pages loads in. If I go to the third page then back to the second, the option for the third page disappears until I return to the first page again

![image](https://cloud.githubusercontent.com/assets/9288431/26382293/483a6370-3ff9-11e7-82cb-665fe77a8c44.png)

![image](https://cloud.githubusercontent.com/assets/9288431/26382288/3d452ba8-3ff9-11e7-9cc1-3c711505fde2.png)

**Comment by lowlandghost** [comment]
Will be solved by #21

**Comment by OneWithTheCore** [comment]
Bug fixed in commit 35f5e82f1f30c50d54c3eba4461417ee550cc101
