### ISSUE TITLE
UI bug with the "## showing, but still loading" text

### ISSUE THREAD

**Issue by OneWithTheCore** [v0lture/project-junebug#24]
![image](https://cloud.githubusercontent.com/assets/9288431/26426693/cd03559a-40a7-11e7-9cf7-dc70a87f60b0.png)

**Comment by OneWithTheCore** [comment]
This bug is also showing with all the other text that shows there:
![image](https://cloud.githubusercontent.com/assets/9288431/26426871/76963fb4-40a8-11e7-999e-f9262099089a.png)

**Comment by lowlandghost** [comment]
Related to how the font handles caps, uncapitalized that message.

**Comment by OneWithTheCore** [comment]
Text misalignment fixed, but when on the third page it says "Showing 40-60 of 50 total"

**Comment by OneWithTheCore** [comment]
Fixed in commit 95364c6004291f24d113a0fb683a00c5de4accae
