### ISSUE TITLE
New bugs are submitted to the end of the page

### ISSUE THREAD

**Issue by lowlandghost** [v0lture/project-junebug#3]
New bugs are shown at the bottom of the page and not at the top where it should appear.

**Comment by OneWithTheCore** [comment]
Bugs are now in nonsensical order

**Comment by lowlandghost** [comment]
Will be solved with #21

**Comment by OneWithTheCore** [comment]
Fixed in commit c1b450a15b29c709c9e76d82463da2abda9feae6
