### ISSUE TITLE
No comments found timeout is not functional in Edge

### ISSUE THREAD

**Issue by lowlandghost** [v0lture/project-junebug#4]
Persistently shows loading or when a new comment is posted comes in it does not close

Confirmed in Edge by @onewiththecore

**Comment by OneWithTheCore** [comment]
This only happens _sometimes_

One the loading thing didn't disappear after waiting ~5 minutes, and another took like 10 seconds to timeout. Happens on the same comment and different comments

**Comment by OneWithTheCore** [comment]
Loading now times out. Fixed at unknown point.
