### ISSUE TITLE
Fix so enter logs in

### ISSUE THREAD

**Issue by OneWithTheCore** [v0lture/project-junebug#6]
When cursor is in password field and user hits enter, it should be like pressing the log in button

**Comment by lowlandghost** [comment]
Applied to register dialog as well

**Comment by lowlandghost** [comment]
Causes refresh in Edge but not in Chrome

**Comment by OneWithTheCore** [comment]
Not what I was talking about. Bug closed

**Comment by OneWithTheCore** [comment]
Need to remove as it causes issues with not being able to log in
